### ISSUE TITLE
Doesn't work with German Passport

### ISSUE THREAD

**Issue by explit28** [bettse/passy#3]
German Passport: 
No reaction

Ukrainian Passport: 
[s]Read Error 63c7
(Log will be attached)[/s]
Works with 1.3

Russian Passport: 
Series 55 (Issued 2020) - works exept
DG3 (Fingerprints)

Series 73 (Issued 2013)
No reaction

**Comment by bettse** [comment]
German passport: https://github.com/AndyQ/NFCPassportReader/issues/22

**Comment by explit28** [comment]
Very weird. My German Passport is very new. 07.2024. And i got absolutely no reaction with Flipper Zero. Will try again.

**Comment by luu176** [comment]
> My German Passport is very new. 07.2024. And i got absolutely no reaction with Flipper Zero. 

I think it's probably the ISO standard being different (just guessing), But I think I fixed that, try to compile the code in this repo and maybe it will work now. Or wait until probably monday-wednesday for it to be available in the flipper app store.

**Comment by bettse** [comment]
New passy v1.1 is out, please test and let me know if it makes any difference: https://lab.flipper.net/apps/passy

**Comment by explit28** [comment]
Hi thanks, tested it.

German Passport: Error 6700 on all fields,
Ukrainian Passport: Same error as before.
Old Russian Passport: Error 6300

So, the passports, which didnt reacted with the previous version - react now, but throw errors...

Looking for further tests...

Thanks

Pawel


 

On Wednesday, 16 April 2025, Eric Betts wrote:
> bettse left a comment (bettse/passy#3)
> 
> New passy v1.1 is out, please test and let me know if it makes any difference: https://lab.flipper.net/apps/passy
> 
> -- 
> Reply to this email directly or view it on itHub:
> https://github.com/bettse/passy/issues/3#issuecomment-2810163590
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***

-- 
Kind regards / Mit freundlichen Grüßen
Pawel Radomychelski

**Comment by bettse** [comment]
Those errors are from https://www.eftlab.com/knowledge-base/complete-list-of-apdu-responses so 
6700: Wrong length
6300: No information given (NV-Ram changed)

The 6300 I thought I saw before during my development when I was doing something wrong, but I cannot recall what.  The 6700 might mean something is shorter or longer than expected, but it's hard to know what.  I may need to start collecting expired passports for testing 😀

**Comment by bettse** [comment]
I pushed a version with a lot more logging, if you can get debug level logs, that would be very useful for tracking down the 6700

**Comment by Willy-JL** [comment]
> Old Russian Passport: Error 6300

@explit28 i had the same error with my italian id card, according to the reference pdf documents in this repo it means:

>Authentication failed
>The protocol (step) failed.

during the BAC auth step.

turns out, for me, my document number included a letter between Q-Z, which were not being calculated correctly on passy. this is fixed with #7 . does that old russian passport happen to contain letters after P in the document number?

**Comment by explit28** [comment]
@Willy-JL The old RU Passport has only numbers in the Passport number. It begins with 73, one blank field and than 7 digits without a single letter.

**Comment by Willy-JL** [comment]
@explit28 i see, not the same issue then.

For logs you need to see them live, they are not stored. Easiest way is with the flipper cli, open https://lab.flipper.net/cli , type `log debug`, then try to read with the app

**Comment by explit28** [comment]
@bettse Old Russian Passport (from 2013, 73 Series) is working now, after Update to 1.2
So Russian Passport can be marked as working.
German and Ukrainian Passports (Both ID card and Travel Passport) still doesn't work  and throw the same errors as before.

**Comment by bettse** [comment]
63CX would be "The counter has reached the value ‘x’ (0 = x = 15) (command dependent)."  No clue what that means.

**Comment by Willy-JL** [comment]
a copy paste of the logs would be useful

**Comment by portasynthinca3** [comment]
Can confirm, both of my Russian passports' (series 73 and 77) DG1 and DG2 are read correctly. DG3 (fingerprints) on the series 77 one fails with error code 6982 ("Security condition not satisfied" according to that page). Pre-series 75 Russian passports don't have DG3s.

**Comment by bettse** [comment]
@explit28 can you try the fap from https://github.com/bettse/passy/actions/runs/14666745500 (inside the passy-f7-api-86.0-1.3.4 zip) with your german passport?  It helped someone else with a 6700 error (https://github.com/bettse/passy/issues/11#issuecomment-2825649800), and might apply in your case.

**Comment by oleksiikutuzov** [comment]
Getting 6a88 error on German residence permit card. Can also provide some logs if it would be helpful.

**Comment by bettse** [comment]
@oleksiikutuzov do you know if that card _should_ work?  I'm not sure.  One test, if your smartphone has NFC, might be to find a passport reader app in the app store/play store and see if that reads it.  if so, then please let me know and send logs 👍 .

**Comment by explit28** [comment]
> [@explit28](https://github.com/explit28) can you try the fap from https://github.com/bettse/passy/actions/runs/14666745500 (inside the passy-f7-api-86.0-1.3.4 zip) with your german passport? It helped someone else with a 6700 error ([#11 (comment)](https://github.com/bettse/passy/issues/11#issuecomment-2825649800)), and might apply in your case.

@bettse On the German Passport i get now Error 6a88, same error like @oleksiikutuzov got.
On Ukrainian Passport - same 63c7

**Comment by bettse** [comment]
I just found something specific to German passports that might be related: https://github.com/AndyQ/NFCPassportReader/issues/205#issuecomment-2041433371

**Comment by explit28** [comment]
As i said in the previus comment, my both German passports are older than 2022. Both issued in July 2024.

**Comment by bettse** [comment]
1. I should have @-mentioned oleksiikutuzov since that is who I was thinking of when writing that
2. The issue mentions the epassport logo, which I think is this (https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/EPassport_logo.svg/117px-EPassport_logo.svg.png): can you confirm you card has that?
3. You commented on that issue: Did you try that person's app/code?  otherwise I think you are interjecting a comment on a conversation that has nothing to do with your situation, and you may want to delete it.

**Comment by explit28** [comment]
> 1. I should have @-mentioned oleksiikutuzov since that is who I was thinking of when writing that
> 
I mentioned @oleksiikutuzov in the previus comment.
>     2. The issue mentions the epassport logo, which I think is this (https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/EPassport_logo.svg/117px-EPassport_logo.svg.png): can you confirm you card has that?

Of course both passport has this logo. can confirm this.
> 
>     3. You commented on that issue: Did you try that person's app/code?  otherwise I think you are interjecting a comment on a conversation that has nothing to do with your situation, and you may want to delete it.

i tried only your commit: https://github.com/bettse/passy/actions/runs/14666745500

Here https://github.com/AndyQ/NFCPassportReader/issues/205#issuecomment-2041433371

i see no code or commit to try...
https://github.com/AndyQ/NFCPassportReader/issues/205#issuecomment-2041433371

**Comment by bettse** [comment]
I think we might be dealing with a slight language issue since some parts of what I was saying I believe may be misunderstood.  That said, thank you for confirming the passport has the logo.


> i see no code or commit to try...

Let me try to be very direct: I think you should not be commenting on that issue, and I think you should delete you comment on that issue.  You should not be participating in that conversation.

**Comment by explit28** [comment]
Ok, understood, i delete my commit.

**Comment by explit28** [comment]
Can Confirm, My Ukrainian Passport works now, when using "ZE001355<" as MRZ. Thanks @oleksiikutuzov for pointing this out. 
Could read 
DG1
DG2
DG3
DG14
DG15
DG5
DG7
DG13

**Comment by bettse** [comment]
@explit28 I think I might know the cause (https://github.com/RfidResearchGroup/proxmark3/issues/1117).  I think your passport might be PACE (https://www.bsi.bund.de/EN/Themen/Oeffentliche-Verwaltung/Elektronische-Identitaeten/Elektronische-Ausweisdokumente/Sicherheitsmechanismen/PACE/pace.html) only.  Passy only does BAC (https://www.icao.int/Security/FAL/PKD/BVRT/Pages/Document-readers.aspx).

**Comment by jo-bitsch** [comment]
Mmmhhh, I'm pretty sure German Passports use BAC as well, as also indicated by https://www.bsi.bund.de/EN/Themen/Oeffentliche-Verwaltung/Elektronische-Identitaeten/Elektronische-Ausweisdokumente/Sicherheitsmechanismen/BAC/bac_node.html#:~:text=BAC%20is%20used%20in%20German%20electronic%20passports.

German ID cards and German residence permit cards on the other hand only use PACE and are not readable at all via BAC.

I am able to read a German passport from 2020 with the following Android App: https://play.google.com/store/apps/details?id=nl.innovalor.nfciddocshowcase which also only works with BAC. So I'm quite confident overall that Passports could work also with Passy.

**Comment by bettse** [comment]
> Mmmhhh, I'm pretty sure German Passports use BAC as well,

I welcome your support debugging this then.  Where is the error during the communication you're seeing?

>  the following Android App ... which also only works with BAC

Is the app open source?  I'm unclear how you are certain it only uses BAC, given that BAC uses the MRZ, and PACE uses the MRZ or a PIN.

> So I'm quite confident overall that Passports could work also with Passy.

Then why doesn't it work?

**Comment by jo-bitsch** [comment]
I can help debugging over the next days. I'll send the logs over and try to look at the relevant code pieces.

This particular Android App is unfortunately not open source, but it definitely only uses the MRZ and no PIN and is advertised to work based on BAC and gives an error message that the German ID card (which is PACE) is not supported.

**Comment by bettse** [comment]
> I can help debugging over the next days. I'll send the logs over and try to look at the relevant code pieces.

I look forward to it!

> is advertised to work based on BAC 

I didn't see any references on the page you linked me.  I searched the page for "BAC" and hadn't found any results.  Where did you see this at?

**Comment by jo-bitsch** [comment]
I also just tried https://github.com/tananaev/passport-reader which is open source and installed via https://f-droid.org/packages/com.tananaev.passportreader/ that one works with the German passport I have available.

**Comment by bettse** [comment]
Can you check the logs while it runs? https://github.com/tananaev/passport-reader/blob/4c7aa91699a6037885c89356d10073f8e445265d/legacy/Passport.java#L226

**Comment by jo-bitsch** [comment]
I installed the new version of passy this morning through https://lab.flipper.net/apps/passy on my flipper and the German passport now works:

DG1 (MRZ) and DG2 (Face) seem to work fine (I masked the personal information):
```
[...]
41573249 [I][PassyReader] Mututal authentication success
[...]
41573505 [I][PassySceneReadCardSuccess] ASN.1 decode success
[...]
41573512 [D][PassySceneReadCardSuccess] DG1: DG1 ::= {
                                                          mrz: P<D<<**************************** }
41625184 [I][Passy] MRZ Info loaded
[...]
41627536 [I][PassyReader] DG2 length: 15375
41627540 [I][PassyReader] Writing offset 88 to /data/DG2.jp2
[...]
```

Excellent job!

**Comment by bettse** [comment]
@jo-bitsch That's awesome although I didn't make any changes intending to fix that, so I'm quite happily confused.

@explit28 Does it work for you?

**Comment by explit28** [comment]
unfortunately it did not work for me with my my new German passports 
ID Card (Personalausweis)
and Travel passport (Reisepass)
as i said, they both are issued in July 2024.
i think it only works with older German passports.

**Comment by jo-bitsch** [comment]
> How old is your German Passport?
From 2020.

**Comment by explit28** [comment]
> > How old is your German Passport?
> 
> From 2020.
> 

its also quite fresh...
very weird....

**Comment by jo-bitsch** [comment]
@explit28 
I'm pretty sure that it will not work with your German ID card (aka nPA or ePA), as those only work via a completely different mechanism (PACE instead of BAC). Regarding the Passport though, I'm not sure.

@bettse This should be the relevant log output:
```
82691685 [D][Iso14443_4aPoller] Read ATS success
82691688 [D][PassyReader] iso14443_4a_event->type 1
82691691 [D][PassyReader] NFC transmit 12: 00a4040c07a0000002471001
82691735 [D][PassyReader] NFC response 2: 9000
82691737 [D][PassyReader] NFC transmit 5: 0084000008
82691749 [D][PassyReader] NFC response 10: 9228d2b4d38f87be9000
82691753 [D][PassyReader] S 32: 00000000000000009228d2b4d38f87be00000000000000000000000000000000
82691758 [D][PassyReader] eifd 32: b6f2ffad4e5e2acf17298ef474847df22c1de2978087e1441177f28d74580ddf
82691763 [D][PassyReader] mifd 8: b630a9e788028ae7
82691767 [D][PassyReader] NFC transmit 46: 0082000028b6f2ffad4e5e2acf17298ef474847df22c1de2978087e1441177f28d74580ddfb630a9e788028ae700
82691878 [D][PassyReader] NFC response 42: 8866d7e1cc8c8423aced915536f9a6e9caa1b0cce90e12b5fa3be39e45780992c2f52fd539f7e4c19000
82691885 [D][PassyReader] decrypted 32: 9228d2b4d38f87be0000000000000000791ae2066a3d27818b15cc47b127b019
82691890 [I][PassyReader] Mututal authentication success
```

**Comment by bettse** [comment]
@jo-bitsch Thanks, although I still have no idea why it works now.  If you go back to a version that doesn't work and see if it gets to "Mututal authentication success", that would be interesting to know.

**Comment by jo-bitsch** [comment]
@bettse The log output with an older version was:
```
85644107 [D][Iso14443_4aPoller] Read ATS success
85644110 [D][PassyReader] iso14443_4a_event->type 1
85644113 [D][PassyReader] NFC transmit 13: 00a4040c07a000000247100100
85644134 [D][PassyReader] NFC response 2: 6700
85644136 [W][PassyReader] Invalid SW 67 00
```

So I think the relevant change was dropping the Le from the select APDU at the start of the exchange (https://github.com/bettse/passy/commit/80befd4e30e507cd6eec3bc1276265330e548b3).

**Comment by bettse** [comment]
> So I think the relevant change was dropping the Le from the select APDU at the start of the exchange (https://github.com/bettse/passy/commit/80befd4e30e507cd6eec3bc1276265330e548b3).

Fully agree, I had (perhaps improperly) assumed when you first joined the thread yesterday that you were experiencing the same error code (6a88) as explit28.

**Comment by jo-bitsch** [comment]
For the fun of it, I just tried the output of the PACE based German ID card (nPA) and residence permits (eAT) with Passy. Both of them will obviously not work with Passy, as they are PACE not BAC, that being said, maybe that explains some of the behavior, some people saw.

That being said: @explit28 reported seeing `6A88` from a residence permit, not from a passport, so I would not expect that to work to begin with, as the residence permit does not use BAC. Of the German identity documents **only the passport supports BAC**.

# nPA
If I run passy with a German ID (Personalausweis, ePA, nPA) from 2020, the output is

```
86955256 [D][Iso14443_4aPoller] Read ATS success
86955259 [D][PassyReader] iso14443_4a_event->type 1
86955262 [D][PassyReader] NFC transmit 12: 00a4040c07a0000002471001
86955314 [D][PassyReader] NFC response 2: 6982
86955317 [W][PassyReader] Invalid SW 69 82
```

Which translates to `Security condition not satisfied.`

Maybe, the error code was changed in the software at some point to return  `SW 6A 88 - Referenced data not found` that others observed. However, I cannot reproduce that.

The technology that https://play.google.com/store/apps/details?id=com.nxp.taginfolite reports is:
```
ISO/IEC 7816-4 compatible
ISO/IEC 14443-4 (Type A) compatible
ISO/IEC 14443-3 (Type A) compatible
```

# eAT
If I run passy with a German residence permit (elektronischer Aufenthaltstitel, eAT) from 2018, the output is 

```
87239989 [D][NfcScanner] Found 1 children
87240018 [I][NfcScanner] Detected 1 protocols
87240020 [E][PassySceneRead] Unknown protocol detected, 1
87240126 [D][NfcScanner] Found 5 base protocols
```

and there is no visible interaction on the screen.

The technology that https://play.google.com/store/apps/details?id=com.nxp.taginfolite reports is:
```
ISO/IEC 7816-4 compatible
ISO/IEC 14443-4 (Type B) compatible
ISO/IEC 14443-3 (Type B) compatible
ISO/IEC 14443-2 (Type B) compatible
```

Flipper NFC Read reports the technology as `ISO14443-3B`

I hope this helps in further debugging the issue, but I suggest that @explit28 shares their logs trying passy with a passport to debug the issue.

Just connect your flipper via USB to your computer, visit https://lab.flipper.net/cli and type `log debug` in the console there and then open passy on your flipper and interact with the passport (Reisepass). You should see the logs in the browser tab.

**Comment by bettse** [comment]
> That being said: explit28 reported seeing 6A88 from a residence permit, not from a passport,

I think you're misreading, they said:

> bettse On the German Passport i get now Error 6a88, same error like oleksiikutuzov got.

> If I run passy with a German ID (Personalausweis, ePA, nPA) from 2020, the output is ... Invalid SW 69 82

That is a very reasonable error response for the situation.

> Flipper NFC Read reports the technology as ISO14443-3B

That's usually a sign it is ISO14443-4B and had bad coupling.

> I suggest that explit28 shares their logs trying passy with a passport to debug the issue.

Totally agree

**Comment by bettse** [comment]
Oh.  I got logs via email from oleksiikutuzov, but they show the 6a88 as a response to the `00820000...` message.

**Comment by jo-bitsch** [comment]
Sorry for misreading it.

I was just able to try with a German passport from 2023 that also exhibits this behavior
```
1846440 [D][Iso14443_4aPoller] Read ATS success
1846443 [D][PassyReader] iso14443_4a_event->type 1
1846446 [D][PassyReader] NFC transmit 12: 00a4040c07a0000002471001
1846594 [D][PassyReader] NFC response 2: 9000
1846597 [D][PassyReader] NFC transmit 5: 0084000008
1846662 [D][PassyReader] NFC response 10: 990438738d742db79000
1846666 [D][PassyReader] S 32: 0000000000000000990438738d742db700000000000000000000000000000000
1846671 [D][PassyReader] eifd 32: 090be47cf9cc9d8be15e2d1ac6458621bc7c3b7ca9717b5ea28af20dced70d0d
1846677 [D][PassyReader] mifd 8: 7aba3ea8a8e62876
1846680 [D][PassyReader] NFC transmit 46: 0082000028090be47cf9cc9d8be15e2d1ac6458621bc7c3b7ca9717b5ea28af20dced70d0d7aba3ea8a8e6287600
1846796 [D][PassyReader] NFC response 2: 6a88
1846798 [W][PassyReader] Invalid SW 6a 88
```

So it seems that indeed the SW of the applet on the secure element of the passports between 2020 and 2023 changed.

**Comment by bettse** [comment]
Awesome, you reproduced!  If you make any progress, I look forward to the PR!

**Comment by jo-bitsch** [comment]
I was looking at the specification (https://www.icao.int/publications/Documents/9303_p11_cons_en.pdf) and noticed in section 4.3.4.2 where Lc and Le are not specified as compared to D.3 Step 6 that the example sets the Lc and Le explicitly to 0x28 (=40 bytes). Passy currently sets it to 0x00 (=256 bytes). Normally setting the allowed return size bigger than necessary is not an issue, but who knows.

I'll try to record an APDU trace with a different passport reader over the next days.

**Comment by bettse** [comment]
> Passy currently sets it to 0x00 (=256 bytes).

Yeah, used to be 0x28 (c158083e2996a0edab531e2a898e0e74a15dc109).  I think that was the fix for your other passport.

**Comment by explit28** [comment]
Just want to share my logs guys:

Its a log of my German Travel Passport (Reisepass), so its not an ID-Card (Personalausweis) nor its a Residence Permit (Aufenthaltserlaubnis).

Read DG1
`19567560 [D][DolphinState] icounter 3566, butthurt 0
19567570 [D][NfcScanner] Found 5 base protocols
19567577 [D][ViewDispatcher] View changed while key press 200106D0 -> 200107C8. Sending key: OK, type: Release, sequence: 00000740 to previous view
19567615 [D][Nfc] FWT Timeout
19567639 [D][Nfc] FWT Timeout
19567702 [D][Nfc] FWT Timeout
19567726 [D][Nfc] FWT Timeout
19567741 [D][NfcScanner] Found 6 children
19567784 [D][Nfc] FWT Timeout
19567788 [D][Nfc] FWT Timeout
19567819 [D][Nfc] FWT Timeout
19567848 [D][Iso14443_4aPoller] Read ATS success
19567881 [D][Iso14443_4aPoller] Read ATS success
19567912 [D][Iso14443_4aPoller] Read ATS success
19567917 [D][EMVPoller] Send select PPSE
19567996 [E][EMVPoller] Failed to parse application
19568013 [I][NfcScanner] Detected 1 protocols
19568120 [I][PassySceneRead] detected 4A protocol
19568126 [I][PassyReader] Passport number: C3FR6CW8M7
19568131 [I][PassyReader] Date of birth: 8003188
19568136 [I][PassyReader] Date of expiry: 3407219
19568142 [D][SecureMessaging] secure_messaging_alloc mrz C3FR6CW8M780031883407219
19568161 [D][Iso14443_4aPoller] Read ATS success
19568166 [D][PassyReader] iso14443_4a_event->type 1
19568172 [D][PassyReader] NFC transmit 12: 00a4040c07a0000002471001
19568254 [D][PassyReader] NFC response 2: 9000
19568259 [D][PassyReader] NFC transmit 5: 0084000008
19568271 [D][PassyReader] NFC response 10: b005c80ef15a167d9000
19568278 [D][PassyReader] S 32: 0000000000000000b005c80ef15a167d00000000000000000000000000000000
19568287 [D][PassyReader] eifd 32: 3ef01f195657507150e69ff1018ef485528dd79906821b30305e8f497eee7607
19568297 [D][PassyReader] mifd 8: a8b72fa9ef4440cb
19568303 [D][PassyReader] NFC transmit 46: 00820000283ef01f195657507150e69ff1018ef485528dd79906821b30305e8f497eee7607a8b72fa9ef4440cb00
19568322 [D][PassyReader] NFC response 2: 6a88
19568326 [W][PassyReader] Invalid SW 6a 88`

`19568326` [W][PassyReader] Invalid SW 6a 88
19591308 [D][BleGap] Start: 4
19591311 [D][BleGap] set_non_discoverable success
19591317 [D][BtSrv] call 0, lock 0x00000000, result 0x00000000
19592490 [D][BtSrv] call 1, lock 0x00000000, result 0x00000000
19592498 [D][GattChar] Updating Battery Level char
19597569 [I][Dolphin] Flush stats
19597572 [I][SavedStruct] Saving "/int/.dolphin.state"
19597606 [I][DolphinState] State saved
19651323 [D][BleGap] Start: 4
19651326 [D][BleGap] set_non_discoverable success
19651332 [D][BtSrv] call 0, lock 0x00000000, result 0x00000000
19695669 [I][Passy] MRZ Info loaded
19695675 [D][ViewDispatcher] View changed while key press 200111F0 -> 200106D0. Sending key: Back, type: Release, sequence: 00000748 to previous view
19711338 [D][BleGap] Start: 4
19711341 [D][BleGap] set_non_discoverable success
19711347 [D][BtSrv] call 0, lock 0x00000000, result 0x00000000
19717490 [D][BtSrv] call 1, lock 0x00000000, result 0x00000000
19717498 [D][GattChar] Updating Battery Level char`

Read DG2
`19875599 [D][Nfc] FWT Timeout
19875668 [D][Nfc] FWT Timeout
19875706 [D][Nfc] FWT Timeout
19875758 [D][Nfc] FWT Timeout
19875781 [D][Nfc] FWT Timeout
19875796 [D][NfcScanner] Found 6 children
19875840 [D][Nfc] FWT Timeout
19875843 [D][Nfc] FWT Timeout
19875884 [D][Nfc] FWT Timeout
19875911 [D][Iso14443_4aPoller] Read ATS success
19875944 [D][Iso14443_4aPoller] Read ATS success
19875975 [D][Iso14443_4aPoller] Read ATS success
19875980 [D][EMVPoller] Send select PPSE
19876075 [E][EMVPoller] Failed to parse application
19876092 [I][NfcScanner] Detected 1 protocols
19876199 [I][PassySceneRead] detected 4A protocol
19876205 [I][PassyReader] Passport number: C3FR6CW8M7
19876210 [I][PassyReader] Date of birth: 8003188
19876215 [I][PassyReader] Date of expiry: 3407219
19876221 [D][SecureMessaging] secure_messaging_alloc mrz C3FR6CW8M780031883407219
19876240 [D][Iso14443_4aPoller] Read ATS success
19876245 [D][PassyReader] iso14443_4a_event->type 1
19876251 [D][PassyReader] NFC transmit 12: 00a4040c07a0000002471001
19876348 [D][PassyReader] NFC response 2: 9000
19876353 [D][PassyReader] NFC transmit 5: 0084000008
19876365 [D][PassyReader] NFC response 10: e3cf0404acb0eb9a9000
19876372 [D][PassyReader] S 32: 0000000000000000e3cf0404acb0eb9a00000000000000000000000000000000
19876381 [D][PassyReader] eifd 32: 3ef01f19565750719425c37a28e0b840a3c4f1b6284d2903c09afd2f5aba1140
19876393 [D][PassyReader] mifd 8: 2521ec1563722f99
19876400 [D][PassyReader] NFC transmit 46: 00820000283ef01f19565750719425c37a28e0b840a3c4f1b6284d2903c09afd2f5aba11402521ec1563722f9900
19876420 [D][PassyReader] NFC response 2: 6a88
19876425 [W][PassyReader] Invalid SW 6a 88
19891385 [D][BleGap] Start: 4
19891388 [D][BleGap] set_non_discoverable success
19891394 [D][BtSrv] call 0, lock 0x00000000, result 0x00000000`

**Comment by jo-bitsch** [comment]
So I recorded the logcat output on Android with the (closed source) app [ReadId Me](https://play.google.com/store/apps/details?id=nl.innovalor.nfciddocshowcase)

```
2025-04-29 00:22:19.974 24146-24155 verifier                nl.innovalor.nfciddocshowcase        I  Setting digest to algorithm SHA-1
2025-04-29 00:22:20.045 24146-24146 ConcurrentReadingTask   nl.innovalor.nfciddocshowcase        I  DocumentType = null
2025-04-29 00:22:20.061 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  Start reading document
2025-04-29 00:22:20.061 24146-24605 ReadNFCDocumentUseCase  nl.innovalor.nfciddocshowcase        I  onDocumentStart: ICAO_MRTD
2025-04-29 00:22:20.061 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  Start primary access control
2025-04-29 00:22:20.192 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  Received APDU: status 9000, length 2
2025-04-29 00:22:20.209 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  Received APDU: status 9000, length 10
2025-04-29 00:22:20.228 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  Received APDU: status 9000, length 36
2025-04-29 00:22:20.260 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  Start PACE for access control
2025-04-29 00:22:20.260 24146-24605 ReadNFCDocumentUseCase  nl.innovalor.nfciddocshowcase        I  onAccessControlStart
2025-04-29 00:22:20.340 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  Received APDU: status 9000, length 2
2025-04-29 00:22:20.413 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  Received APDU: status 9000, length 22
2025-04-29 00:22:20.703 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  Received APDU: status 9000, length 71
2025-04-29 00:22:20.828 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  Received APDU: status 9000, length 71
2025-04-29 00:22:21.017 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  Received APDU: status 9000, length 14
2025-04-29 00:22:21.033 24146-24605 nl.innovalor.nfc.debug  nl.innovalor.nfciddocshowcase        I  End PACE for access control, status: READING
2025-04-29 00:22:21.035 24146-24605 ReadNFCDocumentUseCase  nl.innovalor.nfciddocshowcase        I  onAccessControlFinished: AccessControlStatus[bac: UNKNOWN, pace: PRESENT_SUCCEEDED, eacTA: UNKNOWN, credentialTypesUsed: BAC]
```

Unfortunately, this does not display the C-APDUs, only the receive status and the length of the R-APDUs. That being said: This seems to indicate, that they use PACE with BAC credentials (last line).

So from this it seems like **my previous comment that German passports support BAC was based on outdated information**. The passport used to allow BAC, but some time between 2020 and 2023 it seems to be updated to enforce authentication via PACE. (I checked with the Passport from 2020, using Passy it uses BAC using [ReadId Me](https://play.google.com/store/apps/details?id=nl.innovalor.nfciddocshowcase) it uses PACE)

Also Section 4.1 *Compliant Configurations* of the [specification](https://www.icao.int/publications/Documents/9303_p11_cons_en.pdf) states that PACE only implementations are also compliant and actually will be the only allowed mechanism starting  1 January 2028.

To be able to read these passports will therefore be unfortunately more involved as it will require to implementing PACE with BAC credentials.

PS: @explit28 Thanks for the comment! Your trace still contains the MRZ which includes your complete passport number.

**Comment by explit28** [comment]
Thanks @jo-bitsch, remode the MRZ

**Comment by bettse** [comment]
Given we know the cause, and it's not a bug, but a missing feature, I'm going to close this
